cases:
  case_1:
    memo: trade if the levels are close to each other - we not runing this one anymore
    precondition: all_levels_in(symbol)  # , 'back_test'
    can_replace_level: false
    long:
      level: max(levels['PDH'], levels['PMH'], levels['5MH'])
      cores:
        - breakout_in_last_x_candles(side='up', idx_list=[-5], level=long_level)
        - price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='up', level=long_level)
        - check_entry_vs_retest(side='up', level=long_level)
        - no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
        - check_price_vs_level(side='up', price=price, level=long_level )
        - are_levels_close_to_each_other_for_case_1(side='up')
        - 930 < last_record_hh_mm < 1016 or  mode == 'live'

    short:
      level: min(levels['PDL'], levels['PML'], levels['5ML'])
      cores:
        - breakout_in_last_x_candles(side='down', idx_list=[-5], level=short_level)
        - price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='down', level=short_level)
        - check_entry_vs_retest(side='down', level=short_level)
        - no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
        - check_price_vs_level(side='down', price=price, level=short_level )
        - are_levels_close_to_each_other_for_case_1(side='down')
        - 930 < last_record_hh_mm < 1016 or  mode == 'live'

  case_2:
    memo: This is trading on 5MH and 5ML - release candidate - we not running any more.
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      cores:
        - breakout_in_last_x_candles(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
        - price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='up', level=long_level)
        - check_entry_vs_retest(side='up', level=long_level)
        - no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
        - check_price_vs_level(side='up', price=price, level=long_level )
        - not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
        - 930 < last_record_hh_mm < 1016
    short:
      level: levels['5ML']
      cores:
      - breakout_in_last_x_candles(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
      - price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      - set_and_is_retest_after_breakout(side='down', level=short_level)
      - check_entry_vs_retest(side='down', level=short_level)
      - no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      - check_price_vs_level(side='down', price=price, level=short_level )
      - not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
      - 930 < last_record_hh_mm < 1016

  case_2_1:
    memo: 5MH and 5ML breakout_ver_2, no short above PDH, trade close to level. - we running this one
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      cores:
        - breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
        - price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='up', level=long_level)
        - check_entry_vs_retest(side='up', level=long_level)
        - no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
        - check_price_vs_level(side='up', price=price, level=long_level )
        - not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
        - 930 < last_record_hh_mm < 1016 or mode == 'live'
        - abs (price - long_level) < 1.2 * atr_14
        - price > application_state['symbols'][symbol]['PDL'] and application_state['symbols']['QQQ']['price'] > application_state['symbols']['QQQ']['PDL']
        - price < levels['PDH'] # avoid going long above PDH - extra safety- if we are above PDH, low change we continue after 5MH breakout
    short:
      level: levels['5ML']
      cores:
        - breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
        - price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='down', level=short_level)
        - check_entry_vs_retest(side='down', level=short_level)
        - no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
        - check_price_vs_level(side='down', price=price, level=short_level )
        - not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
        - 930 < last_record_hh_mm < 1016 or  mode == 'live'
        - abs (price - short_level) < 1.2 * atr_14 or 1 == 1
        - price < application_state['symbols'][symbol]['PDH'] and application_state['symbols']['QQQ']['price'] < application_state['symbols']['QQQ']['PDH']
        - price > levels['PDL'] # avoid going short below PDL - extra safety- if we are below PDL, low change we continue after 5ML breakout

#        - qqq['close'].iloc[-2] > qqq['close'].iloc[-3]
#        - QQQ_close_2 > QQQ_close_3


  case_2_2:
    memo: 5MH and 5ML. using breakout_ver_2. GAPs incorporated  - we decided to HOLD this
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      cores:
        - breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
        - price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='up', level=long_level)
        - check_entry_vs_retest(side='up', level=long_level)
        - no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
        - check_price_vs_level(side='up', price=price, level=long_level )
        - not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
        - QQQ_gap_up_in_current_candle()
        - 930 < last_record_hh_mm < 1016 or mode == 'live'
    short:
      level: levels['5ML']
      cores:
        - breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
        - price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='down', level=short_level)
        - check_entry_vs_retest(side='down', level=short_level)
        - no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
        - check_price_vs_level(side='down', price=price, level=short_level )
        - not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
        - QQQ_gap_down_in_current_candle()
        - 930 < last_record_hh_mm < 1016 or  mode == 'live'
  case_4:
    memo: From PDH in first few mins
    can_replace_level: false
    precondition: 1 == 1  # all_levels_in(symbol)
    long:
      level: levels['PDH']
      cores:
        - breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5], level=long_level)
        - price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='up', level=long_level)
        - check_entry_vs_retest(side='up', level=long_level)
        - no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
        - check_price_vs_level(side='up', price=price, level=long_level )
        - abs (price - long_level) < 1.2 * atr_14 or  1 == 1
        - 930 < last_record_hh_mm < 940
    short:
      level: levels['PDL']
      cores:
        - breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5], level=short_level)
        - price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
        - set_and_is_retest_after_breakout(side='down', level=short_level)
        - check_entry_vs_retest(side='down', level=short_level)
        - no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
        - check_price_vs_level(side='down', price=price, level=short_level )
        - abs (price - short_level) < 1.2 * atr_14 or 1 == 1
        - 930 < last_record_hh_mm < 940


scores:
  s1:
    cond: df['VR'].iloc[-1] > 1.2
    score: 4
    memo: Enough volume
  s2:
    cond: intraday_rs_df['rs_rel'].iloc[-1] > 0
    score: 1
    memo: same direction as QQQ
  s3:
    cond: intraday_rs_df['stock_pct'].iloc[-1] < 0.015
    score: 1
    memo: not running too fast. less then 1.5 percent change
  s4:
    cond: qqq_5ML < qqq_df['close'].iloc[-1] < qqq_5MH and qqq_5ML != -1 and qqq_5MH != -1
    score: -4
    memo: 5ML < qqq < 5MH
  s5:
    cond: qqq_df['close'].iloc[-1] > qqq_5MH and qqq_5MH != -1 and market_trend == 'up'
    score: 4
    memo: qqq > 5MH and we going to call
  s6:
    cond: qqq_df['close'].iloc[-1] < qqq_5ML and qqq_5ML != -1 and market_trend == 'down'
    score: 4
    memo: qqq < 5ML and we going to put
  s7:
    cond: 1 == 1
    score: 0
    memo: place holder - ver2.0 of scoring.
