#IMPORTANT: Everytime we run engine it should enable take profit for all symbols. User has to explicitly disable it.
xui_symbol_controls:
  trading_enabled: true
  calls_enabled: true
  puts_enabled: true
  skip_level_closeness_enabled: true # default is false
  skip_pdhl_and_qqq_check_enabled: true # default is false, if true, we will skip the check that avoid going long above PDH - extra safety- if we are above PDH, low change we continue after 5MH breakout.
  symbols:
    QQQ:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AAPL:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AMD:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AMZN:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    NVDA:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    TSLA:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    PLTR:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    SPY:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
