#IMPORTANT: Everytime we run engine it should enable take profit for all symbols. User has to explicitly disable it.
take_profit:
  default_enabled: true
  symbols:
    AAPL:
      tp_enabled: true
    AMD:
      tp_enabled: true
    AMZN:
      tp_enabled: true
    TSLA:
      tp_enabled: true
    NVDA:
      tp_enabled: true
    PLTR:
      tp_enabled: true
    QQQ:
      tp_enabled: true
    SPY:
      tp_enabled: true
    MSFT:
      tp_enabled: true
    GOOG:
      tp_enabled: true
    META:
      tp_enabled: true
    NFLX:
      tp_enabled: true
