  #IMPORTANT: Everytime we run engine it should enable take profit for all symbols. User has to explicitly disable it.
xui_symbol_controls:
  trading_enabled: true
  longs_enabled: true
  shorts_enabled: true
  symbols:
    QQQ:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AAPL:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AMD:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    AMZN:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    NVDA:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    TSLA:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    PLTR:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
    SPY:
      call_enabled: true
      put_enabled: true
      tp_enabled: true
