manual_settings:
  C:
    conditions:
      - QQQ_price >  QQQ_5MH
  P:
    conditions:
      - QQQ_price < QQQ_PML
  symbols:
    AAPL:
      C:
          - 1 == 1
      P:
          - 1 == 8
    AMD:
      C:
          - 1 == 2
      P:
          - 1 == 1
    AMZN:
      C:
        - 1 == 1
      P:
        - 1 == 1
    NVDA:
      C:
          - 1 == 1
      P:
          - 1 == 1
    PLTR:
      C:
          - 1 == 1
      P:
          - 1 == 2
    TSLA:
      C:
          - 1 == 1
      P:
          - TSLA_price < 400

  xblocked_symbols:
    C: ['MU']
    P: ['MU']
  blocked_symbols:
    C: [ 'MU' ]
    P: [ 'MU' ]