manual_settings:
  enable_auto_tp: true
  conditions:
      - QQQ_price >  QQQ_5MH
  P:
    conditions:
      - QQQ_price < QQQ_5MH and QQQ_price < QQQ_PDL
  blocked_symbols:
    C:
      - MU
    P:
      - MU
  symbols:
    AAPL:
      C:
        - 1 == 1
      P:
        - 1 == 1
      tp1: true
      tp2: true
    AMD:
      C:
        - AMD_price > AMD_PDL
      P:
        - AMD_price < AMD_PDL
    AMZN:
      C:
        - AMZN_price > AMZN_PDL
      P:
        - AMZN_price < AMZN_PDL
    NVDA:
      C:
        - NVDA_price > NVDA_PDL
      P:
        - NVDA_price < NVDA_PDL
    PLTR:
      C:
        - PLTR_price > PLTR_PDL
      P:
        - PLTR_price < PLTR_PDL
    TSLA:
      C:
        - TSLA_price > TSLA_PDL
      P:
        - TSLA_price < TSLA_PDL
