manual_settings:
  C:
    conditions:
#      - QQQ_price > QQQ_5MH
#      - QQQ_price > QQQ_5ML
#      - QQQ_price > 602
#      - QQQ_price > QQQ_PML
#      - QQQ_price > QQQ_PDL
      - QQQ_price > QQQ_PDH
  P:
    conditions:
#      - QQQ_price < QQQ_PMH
      - QQQ_price < QQQ_PML
#      - QQQ_price < QQQ_PDL
      - QQQ_price < QQQ_5ML
#      - 1 == -1
#manual_settings:
##  C:
##    conditions:
##      - QQQ_price > QQQ_5ML
##      - QQQ_price > QQQ_PML
###      - QQQ_price > QQQ_PDL
##  P:
##    conditions:
###      - 1 == 2
##      - QQQ_price < QQQ_PML
###      -
##      - QQQ_price < QQQ_5ML
###      -
#
#  C:
#      conditions:
#        - QQQ_price > 626
#        - QQQ_price > QQQ_5ML
#  P:
#      conditions:
#        - QQQ_price < 626
#        - QQQ_price < QQQ_5ML
  symbols:
    QQQ:
      C:
        - 1 == 1
      P:
        - 1 == 1
    AAPL:
      C:
          - 1 == 1
      P:
          - 1 == 1
    AMD:
      C:
          - 1 == 1
      P:
          - 1 == 1
    NVDA:
      C:
          - 1 == 1
      P:
          - 1 == 1
    PLTR:
      C:
          - 1 == 1
      P:
          - 1 == 1
    TSLA:
      C:
          - 1 == 1
      P:
          - 1 == 1
    TSLL:
      C:
          - 1 == 1
      P:
          - 1 == 1
    SPY:
      C:
          - 1 == 1
      P:
          - 1 == 1
    MNQ:
      C:
          - 1 == 1
      P:
          - 1 == 1            -


  blocked_symbols:
    C: ['MU']
    P: ['MU']