live_cases:
  - case_2
  - case_4

positioning:
  capital: 50000
  max_exposure_per_trade: 2000
  min_position_size: 3 #
#  min_contract_entry_price: 0.1  # SB check one is needed
  min_contract_price: 0.1
  stop_after_wins: 10
  max_number_of_trades_per_day: 20
  max_num_of_trade_per_symbol_per_day: 20


trading_session:
  trade_time: 930 < current_hh_mm_ny  < 1559 # TODO change to trade_time
  market_time: 930 < current_hh_mm_ny < 1559
  busy_time: 933 < current_hh_mm_ny < 1016 #don't chaneg this,  we are not saving anythng or any test ...

available_cases:
  - one:
     case: case_2
     memo: 5MH and 5ML breakout_ver_2, no short above PDH, trade close to level. - we running this one - 2.1 improved
  - two:
     case: case_4
     memo: 5MH and 5ML breakout_ver_2, no short above PDH, trade close to level. - we running this one - 2.1 improved
  - three:
     case: case_3
     memo: 5MH and 5ML breakout_ver_2, no short above PDH, trade close to level. - we running this one - 2.1 improved

take_profits_configs:
  t1:
    enabled: true
    close_type: percentage # percentage or absolute
    numner_of_trails: 1
    percentage_change: 0.15
    absolute_change: 0.30
    memo: Taking some profit at 15% or 0.20 with 4 of