# This is used common between all portfolios

symbols_meta:
  QQQ:
    group: Index
    can_trade: false
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
    exchange: CBOE
    expiry_offset: 1
  TSLA:
    group: G1
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 1
    retest_tolerance_multiplier: 1.8
  AAPL:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  NVDA:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  AMD:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  PLTR:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  TSLL:
    group: G1
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.04
    breakout_confirmation_distance: 0.07
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1.8
  SPY:
    group: Index
    can_trade: false
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 2
    exchange: CBOE
    expiry_offset: 1
  MNQ:
    can_trade: false
    contract_type: Future
    min_required_move_from_level: 5
    breakout_confirmation_distance: 2
    chart_entry_offset: 20
    retest_tolerance_multiplier: 3
    contract_month: 202512
    long:
      stop_loss: level_used - ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] + (df['atr_14'].iloc[-2] * 2 )
    short:
      stop_loss: level_used + ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] - (df['atr_14'].iloc[-2] * 2 )
  AMZN:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1


cases:
  case_1:
    memo: trade if the levels are close to each other
    precondition: all_levels_in(symbol)  # , 'back_test'
    can_replace_level: false
    long:
      level: max(levels['PDH'], levels['PMH'], levels['5MH'])
      condition_01: breakout_in_last_x_candles(side='up', idx_list=[-5], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: are_levels_close_to_each_other_for_case_1(side='up')
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09

    short:
      level: min(levels['PDL'], levels['PML'], levels['5ML'])
      condition_01: breakout_in_last_x_candles(side='down', idx_list=[-5], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: are_levels_close_to_each_other_for_case_1(side='down')
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10

  case_2:
    memo: This is trading on 5MH and 5ML - release candidate
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      condition_01: breakout_in_last_x_candles(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['5ML']
      condition_01: breakout_in_last_x_candles(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10

  case_2_1:
    memo: 5MH and 5ML breakout_ver_2, no short above PDH, trade close to level.
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      condition_01: breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
      condition_08: price > application_state['symbols'][symbol]['PDL'] and application_state['symbols']['QQQ']['price'] > application_state['symbols']['QQQ']['PDL']
      condition_08_memo: no long if we below PDL for both symbol and QQQ
      condition_09: 930 < last_record_hh_mm < 1016 or mode == 'live'
      condition_10: abs (price - long_level) < 1.2 * atr_14
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['5ML']
      condition_01: breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
      condition_08: price < application_state['symbols'][symbol]['PDH'] and application_state['symbols']['QQQ']['price'] < application_state['symbols']['QQQ']['PDH']
      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
      condition_10: abs (price - short_level) < 1.2 * atr_14
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10

  case_2_2:
    memo: 5MH and 5ML. using breakout_ver_2. GAPs incorporated  - we decided to HOLD this
    can_replace_level: true
    precondition: all_levels_in(symbol)
    long:
      level: levels['5MH']
      condition_01: breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
      condition_08: QQQ_gap_up_in_current_candle()
      condition_09: 930 < last_record_hh_mm < 1016 or mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['5ML']
      condition_01: breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
      condition_08: QQQ_gap_down_in_current_candle()
      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10

  case_4:
    memo: From PDH
    can_replace_level: false
    precondition: 1 == 1  # all_levels_in(symbol)
    long:
      level: levels['PDH']
      condition_01: breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: abs (price - long_level) < 1.2 * atr_14
#      condition_08: number_of_opened_trades_so_far() == 0
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 940
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['PDL']
      condition_01: breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: abs (price - short_level) < 1.2 * atr_14
#      condition_08: number_of_opened_trades_so_far() == 0
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 940
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10


  case_4_1:
    memo: From PDH
    can_replace_level: false
    precondition: 1 == 1  # all_levels_in(symbol)
    long:
      level: levels['PDH']
      condition_01: breakout_in_last_x_candles_ver_2(side='up', idx_list=[-3,-4,-5], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: abs (price - long_level) < 1.2 * atr_14
#      condition_08: number_of_opened_trades_so_far() == 0
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 940
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['PDL']
      condition_01: breakout_in_last_x_candles_ver_2(side='down', idx_list=[-3,-4,-5], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: abs (price - short_level) < 1.2 * atr_14
#      condition_08: number_of_opened_trades_so_far() == 0
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 940
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10


  case_3:
    memo: This is for Saeed's live test
    can_replace_level: false
    precondition: all_levels_in(symbol) and mode == 'live' and current_hh_mm_ny > 1100
    long:
      level: levels['5MH']
      condition_01: symbol == 'AMD' and 2 == 5000
      condition_02: mode == 'live'
      condition_03: 1 == 1
      condition_04: 1 == 1
      condition_05: 1 == 1
      condition_06: 1 == 1
      condition_07: 1 == 1
      condition_08: 1 == 1
      condition_09: 1 == 1
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08 and eval_buy_condition_09

    short:
      level: levels['5MH']
      condition_01: symbol == 'AMD' and 1 == 2
      condition_02: mode == 'live'
      condition_03: 1 == 1
      condition_04: 1 == 1
      condition_05: 1 == 1
      condition_06: 1 == 1
      condition_07: 1 == 1
      condition_08: 1 == 1
      condition_09: 1 == 1
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09 and eval_sell_condition_10


