ip: "127.0.0.1"
port: 7497
client_id: 250

logging_level: logging.INFO

ws_port: 6107

# before_start:
load_application_state_on_boot: False

api_service:
  port: 5107
  host: 127.0.0.1

interval_seconds:
  engine_loop: .1
  application_state_streamer: 3
  open_trades_streamer: 1
  contract_strikes_streamer: 1
  contract_strikes_force_emit: 15
  quote_cache_streamer: 1
  quote_cache_force_emit: 15

dirs:
  default: "../../portfolios/{portfolio_id}/default"
  results: "../../portfolios/{portfolio_id}/results"
  heartbeat: "../../portfolios/{portfolio_id}/heartbeat"
  ib: "../../portfolios/{portfolio_id}/ib"
  reports: "../../portfolios/{portfolio_id}/reports"
  log_dir: "../../portfolios/{portfolio_id}/logs/{date}"
  intermediate: "../../portfolios/{portfolio_id}/intermediate"
  ohlc: "../../portfolios/{portfolio_id}/backtest-ohlc"
  ohlc_archive: "../../portfolios/{portfolio_id}/ohlc-archive"
  ohlc_w_indicators: "../../portfolios/{portfolio_id}/ohlc-w-indicators"
  charts: "../../portfolios/{portfolio_id}/charts/{date}"

files:
  application_state: "{intermediate}/application_state.json"
  account_info_map: "{intermediate}/account_info_map.json"
  drawing_objects_df: "{charts}/10-drawing_objects_df.csv"
  key_levels_df: "{results}/11-key_levels_df.csv"
  hover_df: "{charts}/12-hover_df.csv"
  close_levels_df": "{charts}/13-close_levels_df.csv"
  candle_info_df: "{charts}/14-candle_info_df.csv"
  screening_log_df: "{charts}/12-screening_log_df.csv"
  order_history_df: "{results}/13-order_history_df.csv"
  stop_loss_history_df: "{results}/14-stop_loss_history_df.csv"
  take_profit_history_df: "{results}/15-take_profit_history_df.csv"
  futures_order_history_df: "{results}/16-futures_order_history_df.csv"
  screening_log_for_run_df: "{results}/17-screening_log_for_run_df.csv" # TODO rename
  screening_summary_df: "{results}/18-screening_summary_df.csv" # TODO rename
  bid_ask_history_df: "{results}/19-bid_ask_history_df.csv" # TODO rename
  screening_summary_agg_df: "{results}/20-screening_summary_agg_df.csv" # TODO rename
  capital_allocation_df: "{results}/21-capital_allocation_df.csv" # TODO rename
  open_close_refs_df: "{results}/22-open_close_refs_df.csv" # TODO rename
  open_close_refs_pnl_df: "{results}/23-open_close_refs_pnl_df.csv" # TODO rename
  capital_flow_df: "{results}/24-capital_flow_df.csv" # TODO rename
  ib_pnl_df: "{ib}/91-ib_pnl_df.csv"
  screening_summary_for_all_sub_runs_agg_df: "{results}/25-screening_summary_for_all_sub_runs_agg_df.csv" # TODO rename
  test_df: "{results}/99-test_df.csv"

#

user_name: User

notification:
  conditions:
    - application_state['is_busy_time']
    - 1 == 1
  recipients: x@yahoo.com
  send_on_signals: true
  send_on_trades: true
  severity:
    high: ["email"]
    medium: []
    low: []



health_check:
  conditions:
    - 920 < current_hh_mm_ny < 1030
  send_email: true
  email_hours: 920 < current_hh_mm_ny < 1030
  email_recipients: x@yahoo.com
  email_interval_minutes: 10
#

features:
  enabled: True
  print_last_few_rows: False
  place_holder_for_features: "for EMA and WAP ...."


alarms:
  enabled: False
  condition: 1 == 1 and  936 <application_state['current_hh_mm_ny'] < 1550
  recipients: x@yahoo.com
  email_interval_minutes: 3
  details:
    - { "level": "5MH", "condition": "df['close'].iloc[-2] > application_state['levels'][symbol]['5MH'] and df['close'].iloc[-3] < application_state['levels'][symbol]['5MH'] " }
    - { "level": "5ML", "condition": "df['close'].iloc[-2] < application_state['levels'][symbol]['5ML'] and df['close'].iloc[-3] > application_state['levels'][symbol]['5ML'] " }


child_configs:
  - config-strategy.yaml
  - config-symbols.yaml
  - config-manual-settings.yaml
  - config-tps.yaml
  - config-xui-symbol-control.yaml
  - config-risk-management.yaml
  - config.local.yaml

historical_data:
  print_last_few_rows: False
