logging_level: logging.INFO

symbols: ['QQQ', 'TSLA', 'AAPL', 'NVDA', 'AMD', 'PLTR', 'TSLL', 'AMZN', 'MNQ', 'SPY']

symbols_meta:
  QQQ:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
    exchange: CBOE
    expiry_offset: 1

  TSLA:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 1
    retest_tolerance_multiplier: 1.8
  AAPL:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  NVDA:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  AMD:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  PLTR:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1
  TSLL:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.04
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1.8
  SPY:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 2
    exchange: CBOE
    expiry_offset: 1
  MNQ:
    can_trade: true
    contract_type: Future
    min_required_move_from_level: 5
    breakout_confirmation_distance: 2
    chart_entry_offset: 20
    retest_tolerance_multiplier: 3
    contract_month: 202512
    long:
      stop_loss: level_used - ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] + (df['atr_14'].iloc[-2] * 2 )
    short:
      stop_loss: level_used + ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
      take_profit: df['close'].iloc[-1] - (df['atr_14'].iloc[-2] * 2 )


  AMZN:
    can_trade: true
    contract_type: Equity
    min_required_move_from_level: 0.25
    breakout_confirmation_distance: 0.15
    chart_entry_offset: 0.5
    retest_tolerance_multiplier: 1

cases:
#  case_1:
#    can_replace_level: false
#    long: # TODO need to be reaned to up_side
#      level: max(levels['PDH'], levels['PMH'], levels['5MH'])
#      condition_01: breakout_in_last_x_candles(side='up', idx_list=[-5], level=long_level)
#      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
#      condition_03: is_retest_after_breakout(side='up', level=long_level)
#      condition_04: check_entry_vs_retest(side='up', level=long_level)
#      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
#      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
#      condition_07: are_levels_close_to_each_other_for_case_1(side='up')
#      condition_08: 1 == 1
#      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
#      condition_10: 1 == 1
#      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
#
#    short:
#      level: min(levels['PDL'], levels['PML'], levels['5ML'])
#      condition_01: breakout_in_last_x_candles(side='down', idx_list=[-5], level=short_level)
#      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
#      condition_03: is_retest_after_breakout(side='down', level=short_level)
#      condition_04: check_entry_vs_retest(side='down', level=short_level)
#      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
#      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
#      condition_07: are_levels_close_to_each_other_for_case_1(side='down')
#      condition_08: 1 == 1
#      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
#      condition_10: 1 == 1
#      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09

  case_2:
    can_replace_level: true
    precondition: 1 == 1
    long:
      level: levels['5MH']
      condition_01: breakout_in_last_x_candles(side='up', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=long_level)
      condition_02: price_retest(side='up', idx_list=[-2,-3,-4], level=long_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='up', level=long_level)
      condition_04: check_entry_vs_retest(side='up', level=long_level)
      condition_05: no_failure_after_breakout(side='up', ohlc_field='close',level=long_level)
      condition_06: check_price_vs_level(side='up', price=price, level=long_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='up', price=price, current_level=long_level, next_levels=['PDH'])
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016 or mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08  and eval_buy_condition_09
    short:
      level: levels['5ML']
      condition_01: breakout_in_last_x_candles(side='down', idx_list=[-3,-4,-5,-6,-7,-8,-9,-10,-11], level=short_level)
      condition_02: price_retest(side='down', idx_list=[-2,-3,-4], level=short_level, both_sides=True )
      condition_03: is_retest_after_breakout(side='down', level=short_level)
      condition_04: check_entry_vs_retest(side='down', level=short_level)
      condition_05: no_failure_after_breakout(side='down', ohlc_field='close',level=short_level)
      condition_06: check_price_vs_level(side='down', price=price, level=short_level )
      condition_07: not is_price_close_to_next_levels_ver_2(side='down', price=price, current_level=short_level, next_levels=['PDL'])
      condition_08: 1 == 1
      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
      condition_10: 1 == 1
      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09

#  case_3:
#    can_replace_level: false
#    long:
#      level: levels['5MH']
#      condition_01: symbol == 'MNQ' and 1 == 2
#      condition_02: mode == 'live'
#      condition_03: 1 == 1
#      condition_04: 1 == 1
#      condition_05: 1 == 1
#      condition_06: 1 == 1
#      condition_07: 1 == 1
#      condition_08: 1 == 1
#      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
#      condition_10: 1 == 1
#      master_condition: eval_buy_condition_01 and eval_buy_condition_02 and eval_buy_condition_03 and eval_buy_condition_04 and eval_buy_condition_05 and eval_buy_condition_06 and eval_buy_condition_07 and eval_buy_condition_07 and eval_buy_condition_08 and eval_buy_condition_09
#
#    short:
#      level: levels['5MH']
#      condition_01: symbol == 'MNQ' and 1 == 2
#      condition_02: mode == 'live'
#      condition_03: 1 == 1
#      condition_04: 1 == 1
#      condition_05: 1 == 1
#      condition_06: 1 == 1
#      condition_07: 1 == 1
#      condition_08: 1 == 1
#      condition_09: 930 < last_record_hh_mm < 1016 or  mode == 'live'
#      condition_10: 1 == 1
#      master_condition: eval_sell_condition_01 and eval_sell_condition_02 and eval_sell_condition_03 and eval_sell_condition_04 and eval_sell_condition_05 and eval_sell_condition_06 and eval_sell_condition_07 and eval_sell_condition_08 and eval_sell_condition_09


stop_losses:
  C:
    stop_loss_condition: underlying_previous_candle_close < level_used_to_open - tolerance_amount and ( level_used_to_open != -1)
#    stop_loss_condition:  symbol == 'AMD' or 1 == 2

  P:
    stop_loss_condition: underlying_previous_candle_close > level_used_to_open + tolerance_amount and ( level_used_to_open != -1)
#    stop_loss_condition:  symbol == 'AMD' or 1 == 1


take_profits:
  t1:
    condition: current_bid > avg_cost_for_1_contract * 1.15 and ( avg_cost_for_1_contract != -1 and current_bid != -1)
    close_quantity_percentage: 0.5

  t2:
    condition: current_bid > avg_cost_for_1_contract * 1.30  and ( avg_cost_for_1_contract != -1 and current_bid != -1)
    close_quantity_percentage: 0.25

  t3:
    condition: current_bid > avg_cost_for_1_contract * 1.6  and ( avg_cost_for_1_contract != -1 and current_bid != -1)
    close_quantity_percentage: -1

  t4_ev:
    condition: >
      (right == 'C' and is_executed_take_profits(symbol, take_profit_list=['t1']) and underlying_previous_candle_close < underlying_open_price)
      or
      (right == 'P' and is_executed_take_profits(symbol, take_profit_list=['t1']) and underlying_previous_candle_close > underlying_open_price)
    close_quantity_percentage: -1
    memo: This is for even break - if we hit TP1, then we go for break even

  t5_cr_lv:
    condition: >
      (right == 'C' and is_price_crossed_levels(side='up', symbol=symbol, next_levels=['PDH'], current_price=underlying_current_price, underlying_open_price=underlying_open_price))
      or
      (right == 'P' and is_price_crossed_levels(side='down', symbol=symbol, next_levels=['PDL'], current_price=underlying_current_price, underlying_open_price=underlying_open_price))
    close_quantity_percentage: 0.5
    memo: if we entered below major level and crossing level, we dump some ...

  t6_trail_t1:
    condition: check_mark_revers_candles(symbol)
    close_quantity_percentage: -1
    memo: for long after tp1, if we go below last down close candle, then we close the position and vice versa for short

  t10_cl_manual:  # This is for closing everything just NVDA:   1 == 1 and symbol == 'NVDA'
    condition: 1 == 2 and symbol == 'MNQ'
    close_quantity_percentage: -1

scores:
  s1:
    cond: df['VR'].iloc[-1] > 1.2
    score: 4
    memo: Enough volume
  s2:
    cond: intraday_rs_df['rs_rel'].iloc[-1] > 0
    score: 1
    memo: same direction as QQQ
  s3:
    cond: intraday_rs_df['stock_pct'].iloc[-1] < 0.015
    score: 1
    memo: not running too fast. less then 1.5 percent change
  s4:
    cond: qqq_5ML < qqq_df['close'].iloc[-1] < qqq_5MH and qqq_5ML != -1 and qqq_5MH != -1
    score: -4
    memo: 5ML < qqq < 5MH
  s5:
    cond: qqq_df['close'].iloc[-1] > qqq_5MH and qqq_5MH != -1 and market_trend == 'up'
    score: 4
    memo: qqq > 5MH and we going to call
  s6:
    cond: qqq_df['close'].iloc[-1] < qqq_5ML and qqq_5ML != -1 and market_trend == 'down'
    score: 4
    memo: qqq < 5ML and we going to put
  s7:
    cond: 1 == 1
    score: 0
    memo: place holder - ver2.0 of scoring.


closeness_distance: df['atr_14'].iloc[-1]

closeness_distance_for_chart:
  live: df['atr_14'].tail(10).mean()
  back_test: df.loc[ (df['date'].dt.time == pd.to_datetime('10:00').time()), 'atr_14' ].mean()  # for BT, we need to get for 10:00 as for BT we don't go candle base...

closeness_distance_for_case_1: df['atr_14'].iloc[-1] * 2

live:
  historical_days: 4 D
  capital: 4000
  capital_per_trade_percentage: 0.20
  max_num_open_trades: 4 # it is not in yet
  num_of_contracts: calculate_number_of_contracts()
  max_num_of_trade_per_symbol_per_day: 2
  max_profit_per_day: 2000 # it will not get into new trade, it is not in yet
  max_loss_per_day: 1000 # it will not get into new trade ... it is not in yet
  is_trade_time: 930 < current_hh_mm_ny  < 1015
  #is_trade_time: 1 == 1
  busy_time: 933 < current_hh_mm_ny < 1016  #don't chaneg this,  we are not saving anythng or any test ...

back_test:
  data:
    get_data_from_ib: true  # we have data from 06-01
    start_date: 2025-11-03
    end_date: 2025-11-14
    historical_days: 5 D  # don't change this
  runs:
    r1:
      active: true
      start: 2025-11-14
      end: 2025-11-14
      memo: run-1
    r2:
      active: false
      start: 2025-11-13
      end: 2025-11-14
      memo: run-2
    r3:
      active: false
      start: 2025-11-13
      end: 2025-11-14
      memo: run-2


  long:
    stop_loss: level_used - ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
    take_profit: ( df['open'].iloc[-1] + df['close'].iloc[-1] ) / 2 + (df['atr_14'].iloc[-2] * 1.5 )
  short:
    stop_loss: level_used + ( dynamic_tolerance.get('tolerance', 0) * app_config['symbols_meta'][symbol].get('retest_tolerance_multiplier', 1))
    take_profit: ( df['open'].iloc[-1] + df['close'].iloc[-1] ) / 2 - (df['atr_14'].iloc[-2] * 1.5 )


chart:
#  source: live
  source: back_test
#  cutoff_in_hours: 0
  hours_in_focus: 3
  live:
    start_time: '09:00'
    end_time: '11:00'

# before_start:
close_all_open_option_positions: false
cancel_open_orders_on_start: false
load_application_state_from_file: true
run_should_take_seconds: 20

user_name: saeed


email:
  send_email: true
#  recipients: vikaskaler.bnr@gmail.com , saeed.bx1@yahoo.com
  recipients: saeed.bx1@yahoo.com

health_check:
  send_email: true
  email_hours: 920 < current_hh_mm_ny < 1030
  email_recipients: saeed.bx1@yahoo.com
  email_interval_minutes: 10

#TODO move to another file ...
exit: false
